### ISSUE TITLE
Broken travis build for PR128

### ISSUE THREAD

**Issue by neilbmclaughlin** [nhsuk/connecting-to-services#131]
I'm guessing it's a time issue again but no time to investigate (pun intended!).

**Comment by neilbmclaughlin** [comment]
Bit of investigation shows the links exist as expected but $(link) shows an empty href attribute - not sure why.

**Comment by neilbmclaughlin** [comment]
From debugging - the list of post codes which have url's added:

LS1 7JH
LS9 7SU
LS1 6BY
LS9 8RZ
LS2 8NG
LS2 8PJ
LS1 5EY
LS9 9JG
LS1 4DT
LS7 1SH

But the postcode of the pharmacy with the missing URL is LS10 1ET

**Comment by neilbmclaughlin** [comment]
I think this a test specific issue as a search for LS27UE (the dataset used is the failing test) on a local copy of master works with all links populated.

**Comment by neilbmclaughlin** [comment]
See PR #132 for illustration of fix.

**Comment by st3v3nhunt** [comment]
Issue #133 should/will fix the problem.

Its because of the objects being references rather than values.
