### ISSUE TITLE
We are limited in tests around opening times due to the use of 'now' 

### ISSUE THREAD

**Issue by neilbmclaughlin** [nhsuk/connecting-to-services#154]
Need to address this by having a mechanism to mock current time.

**Comment by st3v3nhunt** [comment]
Are there specific examples where this is a problem?

I accept the returned value from `isOpen()` is going to vary based on `now()` but this is easily handled by using orgs that are either open all day or closed all day. Here I am specifically talking about the code in `app/lib/getPharmacies.js`

**Comment by st3v3nhunt** [comment]
This is possible within the api app i.e. nhsuk/nearby-services-api
Closing
