### ISSUE TITLE
Add HTTP security headers

### ISSUE THREAD

**Issue by neilbmclaughlin** [nhsuk/connecting-to-services#168]
Concern over the lack of security headers has been raised by others.

While I don't think we have any security vulnerabilities, since we have no exposure to XSS (nunjucks sanitises input) and do not have sensitive data or sessions tokens,  it seems prudent to introduce these best practice measures sooner rather than later.

**Comment by st3v3nhunt** [comment]
I think this is all sorted now via a number of PRs including:

* #178 
* #177 
* #170 
* #167 
* #166

@neilbmclaughlin Can this be closed?

**Comment by st3v3nhunt** [comment]
Closing as it has been rectified.
