### ISSUE TITLE
Tests/Lint may pass locally but fail on CI due to unstaged files

### ISSUE THREAD

**Issue by neilbmclaughlin** [nhsuk/connecting-to-services#189]
Not an issue specific to this repo but the current githooks will allow a commit which passes lint and tests locally in the presence of unstaged files. A subsequent push can then break the build.

The pre-commit hook should probably (or at least warn) fail if there are unstaged files. The developer would then have to manually stash the files if they were not for commit in order for the local build to pass the commit hook checks.

There are a few examples around which use `git diff --exit-code`. Initial experimentation suggests that `git status` doesn't return a non-zero exit code if there are no changes but this might need more investigation.

**Comment by neilbmclaughlin** [comment]
See [here](https://github.com/nhsuk/moment-opening-times/pull/41) for an example from the moment-opening-times.

**Comment by st3v3nhunt** [comment]
Closing the issue as it doesn't tend to cause problems and is unlikely to be implemented.
