### ISSUE TITLE
Setup environment variables in Azure

### ISSUE THREAD

**Issue by st3v3nhunt** [nhsuk/connecting-to-services#21]
Since the environment variables have been added they need to be setup for the Azure instances:

* `NHSCHOICES_SYNDICATION_APIKEY`
* `NHSCHOICES_SYNDICATION_BASEURL`

**Comment by neilbmclaughlin** [comment]
I get that setting up a webapp is a one shot thing (so can be done manually through the UI) but making changes to it are ongoing.

I think we should be looking at scripting the addition of things like env vars.

**Comment by st3v3nhunt** [comment]
Environment variables have been added. However, the application is not working due to the submodule cloning during the retrieval of the code. Need to get this sorted as a priority.

**Comment by st3v3nhunt** [comment]
See PR #51 for additional information.

The PR includes the fix for the environment not working.

**Comment by st3v3nhunt** [comment]
Both Azure environments are working and have the necessary env vars added. The issue of managing them in a more automated fashion is a separate issue.
