### ISSUE TITLE
Add shellcheck for bash linting

### ISSUE THREAD

**Issue by neilbmclaughlin** [nhsuk/connecting-to-services#235]
With the introduction of bash scripts for docker and rancher on we should add shellcheck (https://www.shellcheck.net/) to our git hooks.

If we stick with the python scripts we will also need a python linter too.

This will apply to other repo's too.

**Comment by st3v3nhunt** [comment]
Closing the issue as it was originally created when the deployment scripts that are now part of [nhsuk/ci-deployment](/nhsuk/ci-deployment) were part of the repo.
