### ISSUE TITLE
Stop using GitHub personal access tokens on Travis

### ISSUE THREAD

**Issue by neilbmclaughlin** [nhsuk/connecting-to-services#252]
This may not be possible but here to allow us to explore/discuss the options.

**Comment by st3v3nhunt** [comment]
Is this a case of replacing it with an OAuth token generated from the org level?

**Comment by neilbmclaughlin** [comment]
I couldn't see anything at the org level but it may be because I'm not an org admin.

**Comment by st3v3nhunt** [comment]
Try again

**Comment by st3v3nhunt** [comment]
Closing this as we are no longer using an individual's access token
