### ISSUE TITLE
Handle no opening times

### ISSUE THREAD

**Issue by st3v3nhunt** [nhsuk/connecting-to-services#27]
Search for `hg2` - the second result 'Day Lewis Pharmacy' has no opening times.

**Comment by st3v3nhunt** [comment]
Should a default message be used when an org has no opening times?
Should the org be omitted from the 'only open' results but included in the 'everything' results?
Should the application 'break'?

**Comment by neilbmclaughlin** [comment]
Discussed in review with @mcgrathjoe and @ermlikeyeah 

When no opening times display 'Call for opening times'
Include these orgs only in everything results
Application should handle this scenario

Resolved by PR #40
