### ISSUE TITLE
Scottish pharmacy finder link specificity update

### ISSUE THREAD

**Issue by beseven** [nhsuk/connecting-to-services#302]
There seems to be a better link for searching for pharmacies in Scotland:
https://www.nhsinform.scot/national-service-directory/pharmacies
compared to the one we have at the moment
http://www.nhs24.com/findlocal/

**Comment by st3v3nhunt** [comment]
This has been changed https://github.com/nhsuk/connecting-to-services/commit/fb4369f40b4bba545744525bc02f805c9d11dcbe#diff-6678c4ae7af7044db7b7428a051a6177R21
