### ISSUE TITLE
'Opens in 0 minutes' message

### ISSUE THREAD

**Issue by neilbmclaughlin** [nhsuk/connecting-to-services#359]
We get this odd message when checking at, say, 07:29 for a pharmacy with a 08:00 opening time.

I think it is because we round down 'minutes until open' which gives us the odd message.

**Comment by st3v3nhunt** [comment]
Fixed by the change in `nearby-services-api` https://github.com/nhsuk/nearby-services-api/commit/fdfc6258dc5a47b83cf92b86f6d12c15c958cb03
