### ISSUE TITLE
Build failing due to test execution times

### ISSUE THREAD

**Issue by neilbmclaughlin** [nhsuk/connecting-to-services#39]
https://travis-ci.org/nhsuk/connecting-to-services/builds/162109811

The code requires calls to 100 pharmacy overview pages and, even when mocked, this takes longer  on travis than the test timeout parameter.

The tests were previously passing as only the first 10 calls were mocked. After that the code was failing silently, opening times were therefore not parsed and, as an unintended consequence, the tests ran faster. The new tests do not allow this to happen and all 100 calls are mocked resulting in slower test execution.

I'll give it some thought but any suggestions welcome.

**Comment by st3v3nhunt** [comment]
Due to the change in application architecture this is no longer a concern. Issue closed.
