### ISSUE TITLE
Sort out CDN font path

### ISSUE THREAD

**Issue by st3v3nhunt** [nhsuk/connecting-to-services#59]
Load a page and check the console for errors. A number of resources are not available i.e. not found due to the path in the `.css` file not having the variable that is used in the `SCCS` replaced.

This needs sorting so that the font files are being mapped to the correct CDN host.

**Comment by neilbmclaughlin** [comment]
Example from chrome dev tools:
```
http://localhost:3000/*%20@echo%20FONT_CDN_PATH%20*/assets/fonts/fsme/FSMeWeb-Regular.woff Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:3000/*%20@echo%20FONT_CDN_PATH%20*/assets/fonts/fsme/FSMeWeb-Bold.woff Failed to load resource: the server responded with a status of 404 (Not Found)

```
