### ISSUE TITLE
Consider using npm shrinkwrap to fix dependencies

### ISSUE THREAD

**Issue by neilbmclaughlin** [nhsuk/connecting-to-services#64]
As part of my investigations into the failing build yesterday I was looking at the package versioning we employ. 

Looking at the meaning of ^ in package versioning, it only fixes the major version [1]. This means that, for a given package, we are exposed to bad semantic versioning on the part of a publisher or simply a bug in a later minor version. This applies to our direct dependencies and, importantly, the chain of dependencies below them. The end result could be subtle differences between our environments.

We need to consider where using shrinkwrap [2] in our deployment pipeline would help. 

[1] http://stackoverflow.com/questions/22343224/difference-between-tilde-and-caret-in-package-json
[2]  See `npm help shrinkwrap`

**Comment by st3v3nhunt** [comment]
Closing seen as the repo is now using `npm shrinkwrap`
